### ISSUE TITLE
Extracting all possible plans fails for RPG domain

### ISSUE THREAD

**Issue by meneguzzi** [pucrs-automated-planning/javagp#21]
Running

```
javagp -extractAllPossibleSolutions 9 -d rpgddl -p pb1.pddl
```

In the RPG domain makes the planner continue well beyond length 9 plans and never returns the actual solution of length 9.

[pb1.txt](https://github.com/pucrs-automated-planning/javagp/files/475759/pb1.txt)
[rpg.txt](https://github.com/pucrs-automated-planning/javagp/files/475760/rpg.txt)

@guilhermekrz, can you check this?

**Comment by guilhermekrz** [comment]
Ok, just to clarify what this parameter does (maybe it is not clear):
- It finds the optimal solution at level "k"
- It expands "n" more levels, where "n" is equal to the input argument from "extractAllPossibleSolutions"
- It returns all possible solutions at level "k" + "n"

So `javagp -extractAllPossibleSolutions 9 -d rpgddl -p pb1.pddl` does not necessarily return plans with length 9.

We could:
- Find a better argument name and fix its description (to clarify its expected behavior);
- Add another parameter that actually finds plans with the specified length. In order to do this, if I am not mistaken, we would need to expand the graph until it reaches level "n", extract all possible solutions and filter those solutions with length "n".

Thoughts?

---

Testing in my machine running this command `javagp -extractAllPossibleSolutions n -d rpgddl -p pb1.pddl`, varying parameter "n" ("n" -> time):
5 -> 3s
6 - > 9s
7 -> 31s
8 -> 2m37s
9 - >14m, but "java.lang.OutOfMemoryError: Java heap space"

**Comment by meneguzzi** [comment]
Got it, I agree that we need to improve documentation of the feature in the command line. 
In any case, where does the planner write the alternative plans? I expected to see something on the screen, but to me it looked like it went straight through level 9 (where at least one plan should have been found).

**Comment by guilhermekrz** [comment]
It logs in the console all alternative plans , but only after finishing (reaching last graph level). I am not logging right after finding the optimal plan because it ends up lost between logs of 
`INFO: Expanding graph
INFO: Extracting solution`

Example:
INFO: Number of plan founds: 12
INFO: ---------------------
INFO: Plan found:
[move(room8,room4), destroy(room4), pickup(room4), move_with_sword(room4,room7), move(room7,room6), destroy(room6), move(room6,room5), move(room5,room2), disarm(room2), move(room2,room1)]
INFO: Plan length: 10
INFO: ---------------------
INFO: Plan found:
[destroy(room8), move(room8,room4), pickup(room4), move_with_sword(room4,room3), move(room3,room6), destroy(room6), move(room6,room5), move(room5,room2), disarm(room2), move(room2,room1)]
INFO: Plan length: 10
INFO: ---------------------
INFO: Plan found:
[move(room8,room4), pickup(room4), move_with_sword(room4,room7), move(room7,room6), move(room6,room5), destroy(room5), move(room5,room2), disarm(room2), move(room2,room1)]
INFO: Plan length: 9
....

**Comment by meneguzzi** [comment]
Got it, I realized it worked that way and closed the issue :-D.
